# Generated by Django 5.0.6 on 2024-05-11 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_homepage_page_ptr_alter_comment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 18, 28, 45, 923251, tzinfo=datetime.timezone.utc)),
        ),
    ]
